### ISSUE TITLE
Not work on Ubuntu Core 22

### ISSUE THREAD

**Issue by profsoft** [MirServer/mir-kiosk-x11-snap#18]
Tested on Ubuntu Core 22 + Ubuntu Frame on Raspbery Pi Zero 2 W.
Because not exist inotifywait

++ '[' -e /run/user/1000/wayland-0 ']'
++ wait 38257
++ inotify_pid=38261
++ '[' -e /run/user/1000/wayland-0 ']'
++ sleep 2
+++ dirname /run/user/1000/wayland-0
++ inotifywait --event create /run/user/1000
/snap/avalonia-test/x1/hacks/setup-wayland-host: line 14: /snap/avalonia-test/x1/usr/bin/inotifywait: cannot execute binary file: Exec format error

**Comment by AlanGriffiths** [comment]
The error message you show:

    cannot execute binary file: Exec format error

indicates that `inotifywait` does exist, but is a binary for a different architecture. That is a problem with the packaging of "avalonia-test", not a bug in mir-kiosk-x11-snap
