### ISSUE TITLE
UI Sometimes Isn't Launched

### ISSUE THREAD

**Issue by daleknauss** [MirServer/mir-kiosk-x11-snap#9]
We've had to move from wayland to xwayland on our Ubuntu Core based system due to various issues. We're still using mir-kiosk but have switched to using this snap to launch our UI. Since making the switch, we are occasionally (1 out of 5-10 times) seeing an issue at boot up where the UI isn't launched.

Oddly, once I ssh in to the device, the UI starts as normal. 

I'm not able to find anything in the logs that looks different between successful and unsuccessful sessions.

Thank you.

**Comment by AlanGriffiths** [comment]
When you say "the UI isn't launched" do you mean that mir-kiosk doesn't start (orange flash)? Or that your application doesn't start?

As you mention switching to xwayland and raise this here, I assume that Mir is starting and something isn't working in your snap. Obviously, as you've not attached logs I cannot see anything significant in them either.

I've not been able to reproduce this problem, but I have noticed a difference in the startup logic in `mir-kiosk-snap-launch` (the Wayland equivalent of this - #10).

**Comment by noharvey** [comment]
Here are logs of the issue: there is a 2 minute gap and you can see an ssh in starts the UI.

Oct 04 23:05:29 FMTRMRD2A000008 sshd[4507]: Accepted password for forme from 192.168.1.104 port 60380 ssh2
Oct 04 23:05:29 FMTRMRD2A000008 sshd[4507]: pam_unix(sshd:session): session opened for user forme by (uid=0)
Oct 04 23:05:29 FMTRMRD2A000008 interactive-strength-studio.ui[2248]: /run/user/ CREATE,ISDIR 100
[TextFile4.txt](https://github.com/MirServer/mir-kiosk-x11-snap/files/7287515/TextFile4.txt)

**Comment by AlanGriffiths** [comment]
There's no gap between those two events. Nor do they appear to be from anything in this project.

We need a log of what happen leading up to the problem or there's no way to assist.

**Comment by AlanGriffiths** [comment]
(Received some logs privately)
